[tool.poetry]
name = "pallet flow"
version = "0.1.0"
description = ""
authors = ["Julio Cezar Riffel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.6"
simpy = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

